const producto = 'monitor 32"';
console.log(producto.toUpperCase());// convierte una cadena de texto de minuscula a mayuscula...
console.log(producto.toLowerCase());//metodo que covierte una cadena de texto de mayuscula a minuscula...

const email= "Correo@correo.com";
const email2 = "Adan@correo.com";
console.log(email.toLowerCase());// convierte una cadena de string de mayuscula a minuscula...
console.log(email2.toUpperCase());// convierte una cadena de string de minuscula a mayuscula...

const precio = 300;// 
console.log(precio); // imprime el valor de un entero...
console.log(precio.toString());// convierte el valor entero a un String...